In [1]:
import numpy as np
np.random.seed(0)

In [2]:
x = np.arange(5)
y = np.empty(5)

In [3]:
np.multiply(x, 10, out=y)

array([ 0., 10., 20., 30., 40.])

In [4]:
y

array([ 0., 10., 20., 30., 40.])

In [5]:
y = np.zeros(10)

In [6]:
np.power(2, x, out=y[::2])

array([ 1.,  2.,  4.,  8., 16.])

In [7]:
y

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

In [8]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [9]:
np.multiply.reduce(x)

120

In [10]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [11]:
5*4*3*2*1

120

In [14]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [15]:
L = np.random.random(100)
sum(L)

47.27938395125176

In [16]:
np.random.random?

In [17]:
np.sum(L)

47.279383951251766

In [18]:
big_array = np.random.rand(1000000)

In [19]:
%timeit sum(big_array)

88.7 ms ± 3.13 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [20]:
%timeit np.sum(big_array)

598 µs ± 5.85 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [21]:
sum(big_array)

500385.08749076794

In [22]:
np.sum(big_array)

500385.0874907551

In [23]:
np.random.rand?

In [24]:
big_array[:10]

array([0.67781654, 0.27000797, 0.73519402, 0.96218855, 0.24875314,
       0.57615733, 0.59204193, 0.57225191, 0.22308163, 0.95274901])

In [25]:
big_array.sum()

500385.0874907551

In [26]:
big_array.min()

7.071203171893359e-07

In [27]:
big_array.max()

0.9999997207656334

In [28]:
big_array.dtype

dtype('float64')

In [29]:
M = np.random.random((3, 4))
M

array([[0.65527872, 0.53859662, 0.1160128 , 0.88693339],
       [0.78005386, 0.29509276, 0.23792159, 0.36427966],
       [0.28696762, 0.13911998, 0.81564486, 0.33446842]])

In [30]:
M.sum()

5.450370274366079

In [31]:
M.min(axis=0)

array([0.28696762, 0.13911998, 0.1160128 , 0.33446842])