In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [3]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [4]:
x1

array([5, 0, 3, 3, 7, 9])

In [5]:
x1 = np.random.randint(0, 10, (6,))
x1

array([4, 3, 4, 4, 8, 4])

In [6]:
x3.ndim

3

In [7]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [8]:
print("ndim", x3.ndim)
print("shape", x3.shape)
print("size", x3.size)

ndim 3
shape (3, 4, 5)
size 60


In [9]:
print("dtype", x3.dtype)

dtype int64


In [10]:
x3.itemsize

8

In [11]:
x3.nbytes

480

In [13]:
x3.size * x3.itemsize

480

In [14]:
x1

array([4, 3, 4, 4, 8, 4])

In [15]:
x1[0]

4

In [16]:
x1[4]

8

In [17]:
x1[-1]

4

In [18]:
x1[-2]

8

In [19]:
x1[-5]

3

In [20]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [21]:
x2[1,1]

6

In [22]:
x2[-1, -3]

6

In [23]:
x2[-1, -3] = 19
x2

array([[ 3,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1, 19,  7,  7]])

In [24]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
x[:5]

array([0, 1, 2, 3, 4])

In [26]:
x[5:]

array([5, 6, 7, 8, 9])

In [27]:
x[4:7]

array([4, 5, 6])

In [28]:
x[::2]

array([0, 2, 4, 6, 8])

In [29]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [30]:
x[5::-2]

array([5, 3, 1])

In [31]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1, 19,  7,  7]])

In [ ]:
x2[:]