In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])

a + b

array([5, 6, 7])

In [3]:
a + 5

array([5, 6, 7])

In [4]:
5 + a

array([5, 6, 7])

In [5]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
a

array([0, 1, 2])

In [7]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [8]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

In [9]:
b

array([[0],
       [1],
       [2]])

In [10]:
b.shape

(3, 1)

In [11]:
a

array([0, 1, 2])

In [12]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [13]:
a.shape

(3,)

In [14]:
b.shape

(3, 1)

In [15]:
a.ndim

1

In [16]:
b.ndim

2

In [17]:
M = np.ones((2,3))
a = np.arange(3)

In [18]:
M.shape

(2, 3)

In [19]:
a.shape

(3,)

In [20]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [21]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)

In [22]:
a.shape

(3, 1)

In [23]:
b.shape

(3,)

In [24]:
X = np.random.random((10, 3))
X

array([[0.43184726, 0.00547606, 0.58447314],
       [0.65698101, 0.959517  , 0.39153346],
       [0.84746484, 0.75942803, 0.80431385],
       [0.48058428, 0.88171325, 0.6457826 ],
       [0.29237228, 0.27080364, 0.5214176 ],
       [0.56797379, 0.92442424, 0.03949349],
       [0.91447653, 0.51384365, 0.24104303],
       [0.26691344, 0.07254367, 0.01606781],
       [0.21448295, 0.82694604, 0.992033  ],
       [0.56813057, 0.95158775, 0.44598934]])

In [25]:
X.mean(axis=1)

array([0.34059882, 0.66934383, 0.80373557, 0.66936004, 0.36153117,
       0.5106305 , 0.5564544 , 0.11850831, 0.67782067, 0.65523589])

In [27]:
X_mean = X.mean(axis=0)

In [28]:
X_centered = X - X_mean
X_centered

array([[-0.09227543, -0.61115227,  0.1162584 ],
       [ 0.13285831,  0.34288867, -0.07668127],
       [ 0.32334214,  0.14279969,  0.33609912],
       [-0.04353841,  0.26508491,  0.17756787],
       [-0.23175041, -0.3458247 ,  0.05320287],
       [ 0.0438511 ,  0.3077959 , -0.42872125],
       [ 0.39035383, -0.10278468, -0.2271717 ],
       [-0.25720926, -0.54408466, -0.45214692],
       [-0.30963974,  0.21031771,  0.52381827],
       [ 0.04400788,  0.33495942, -0.0222254 ]])

In [29]:
X_mean.shape

(3,)

In [30]:
X.shape

(10, 3)

In [31]:
X_centered.mean(axis=0)

array([-1.11022302e-17, -2.22044605e-17, -6.10622664e-17])