In [1]:
import numpy as np
np.random.seed(0)

In [2]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [3]:
values = np.random.randint(1, 10, (5,))
values

array([6, 1, 4, 4, 8])

In [4]:
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [5]:
big_array = np.random.randint(1, 100, (1000000,))

In [6]:
%timeit
compute_reciprocals(big_array)

array([0.1       , 0.01190476, 0.04545455, ..., 0.01428571, 0.01098901,
       0.01149425])

In [7]:
%timeit compute_reciprocals(big_array)

5.45 s ± 574 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
%timeit (1.0 / big_array)

3.48 ms ± 76.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [10]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [11]:
np.arange(9).shape

(9,)

In [12]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
np.arange(9)[:, np.newaxis].shape

(9, 1)

In [16]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [17]:
x + 5

array([5, 6, 7, 8])

In [18]:
x - 5

array([-5, -4, -3, -2])

In [19]:
x * 2

array([0, 2, 4, 6])

In [20]:
x / 2

array([0. , 0.5, 1. , 1.5])

In [21]:
x // 2

array([0, 0, 1, 1])

In [22]:
 2 / 3

0.6666666666666666

In [23]:
2 // 3

0

In [24]:
-x

array([ 0, -1, -2, -3])

In [25]:
x ** 2

array([0, 1, 4, 9])

In [26]:
x % 2

array([0, 1, 0, 1])

In [28]:
-(0.5 * x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [29]:
2 + x

array([2, 3, 4, 5])

In [30]:
np.add(2, x)

array([2, 3, 4, 5])

In [31]:
x = np.array([-2, -1, 0, 1, 2])
x

array([-2, -1,  0,  1,  2])

In [32]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [33]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [34]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j])
np.abs(x)

array([5., 5., 2.])

In [35]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [36]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [37]:
x = [-1, 0, 1]
np.arcsin(x)

array([-1.57079633,  0.        ,  1.57079633])

In [38]:
np.arccos(x)

array([3.14159265, 1.57079633, 0.        ])

In [39]:
x = [1,2,3]
x = np.arange(1,4)
x

array([1, 2, 3])

In [40]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [41]:
np.exp2(x)

array([2., 4., 8.])

In [42]:
np.power(2, x)

array([2, 4, 8])

In [43]:
np.power(x, 2)

array([1, 4, 9])

In [44]:
x = [1,2,4,10]

In [45]:
np.log(x)

array([0.        , 0.69314718, 1.38629436, 2.30258509])

In [46]:
np.log(np.exp(1))

1.0

In [47]:
np.log2(x)

array([0.        , 1.        , 2.        , 3.32192809])

In [48]:
np.log10(x)

array([0.        , 0.30103   , 0.60205999, 1.        ])