In [1]:
import numpy as np
np.random.seed(0)

In [2]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [3]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [4]:
z = np.array([99, 99, 99, 90])

In [5]:
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99, 90])

In [6]:
grid = np.array([[1,2,3],
                [4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [8]:
grid.shape

(2, 3)

In [11]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [12]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                [6,5,4]])

In [13]:
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [14]:
np.vstack([grid, x])

array([[9, 8, 7],
       [6, 5, 4],
       [1, 2, 3]])

In [15]:
y = np.array([[99],
             [99]])

In [16]:
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [17]:
x = [1,2,3, 99, 99, 3,2,1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [18]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
np.hsplit(grid, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [25]:
upper, lower = np.vsplit(grid, [2])
print(upper, lower, sep='\n\n')

[[0 1 2 3]
 [4 5 6 7]]

[[ 8  9 10 11]
 [12 13 14 15]]


In [21]:
np.vsplit(grid, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [27]:
left, mid, right = np.hsplit(grid, [1,3])
print(left, mid, right, sep="\n\n")

[[ 0]
 [ 4]
 [ 8]
 [12]]

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]

[[ 3]
 [ 7]
 [11]
 [15]]
