In [2]:
import numpy as np

In [3]:
rand = np.random.RandomState(42)

In [4]:
x = rand.randint(0, 100, 10)
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [5]:
[x[3], x[7], x[2]]

[71, 86, 14]

In [6]:
ind = [3, 7, 4]
x[ind]

array([71, 86, 60])

In [7]:
ind = np.array([[3, 7],
               [4, 5]])
x[ind]

array([[71, 86],
       [60, 20]])

In [8]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

array([ 2,  5, 11])

In [10]:
row[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [13]:
col

array([2, 1, 3])

In [14]:
row[:, np.newaxis].shape

(3, 1)

In [15]:
col.shape

(3,)

In [11]:
0 0 0 0   1 0 1 0
1 1 1 1   1 0 1 0
2 2 2 2   1 0 1 0

SyntaxError: invalid syntax (4152953747.py, line 1)

In [12]:
X[row[:, np.newaxis], col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [16]:
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
