In [1]:
import numpy as np

In [2]:
np.__version__

'1.22.2'

In [3]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
import array

In [5]:
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [7]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [8]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [9]:
np.array([range(i, i + 3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [10]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [12]:
np.ones((3, 5), dtype=np.float16)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float16)

In [13]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [14]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
np.arange(0, 15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
np.random.random((3,3))

array([[0.50754111, 0.96830376, 0.90559548],
       [0.65253276, 0.75112062, 0.0707519 ],
       [0.72331407, 0.35483341, 0.21541954]])

In [18]:
np.random.normal(0, 1, (3,3))

array([[ 0.07254322,  0.55257726,  0.97322293],
       [-0.40733092,  1.37180896, -1.36387424],
       [-1.54265982,  0.94785867,  0.13589048]])

In [19]:
np.random.randint(0, 10, (3,3))

array([[1, 3, 3],
       [0, 2, 1],
       [0, 8, 4]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.empty(3)

array([1., 1., 1.])

In [23]:
np.zeros(5, dtype='int')

array([0, 0, 0, 0, 0])

In [24]:
np.zeros(5, dtype='int16')

array([0, 0, 0, 0, 0], dtype=int16)

In [25]:
np.zeros(5, dtype=np.int16)

array([0, 0, 0, 0, 0], dtype=int16)