In [1]:
import numpy as np
np.random.seed(0)
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [2]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [3]:
x2[0,0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [6]:
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [7]:
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [8]:
x2[::-1]

array([[ 1,  6,  7,  7],
       [ 7,  6,  8,  8],
       [12,  5,  2,  4]])

In [9]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [11]:
x2[:, 0]

array([12,  7,  1])

In [12]:
x2_sub = x2[:2, :2]
x2_sub

array([[12,  5],
       [ 7,  6]])

In [13]:
x2_sub[0, 0] = 99
x2_sub

array([[99,  5],
       [ 7,  6]])

In [14]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [15]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy

array([[99,  5],
       [ 7,  6]])

In [16]:
x2_sub_copy[0, 0] = 42
x2_sub_copy

array([[42,  5],
       [ 7,  6]])

In [17]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [18]:
grid = np.arange(1, 10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
x1

array([5, 0, 3, 3, 7, 9])

In [20]:
x1.shape

(6,)

In [21]:
x1.reshape((1,6))

array([[5, 0, 3, 3, 7, 9]])

In [22]:
x1.reshape((6,1))

array([[5],
       [0],
       [3],
       [3],
       [7],
       [9]])

In [23]:
x1

array([5, 0, 3, 3, 7, 9])

In [24]:
x1[np.newaxis, :]

array([[5, 0, 3, 3, 7, 9]])

In [25]:
x1[:, np.newaxis]

array([[5],
       [0],
       [3],
       [3],
       [7],
       [9]])